name: release
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: restore cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.cache/deno

      - name: cache
        run: DENO_DIR=./deno deno cache --import-map=import_map.json --no-check deps.ts aleph.config.ts _utils.ts

      - name: build
        run: |
          deno run -A https://deno.land/x/aleph/install.ts
          deno run -A _tools/build_worker.ts 
          aleph build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAPCSS_5B66C }}'
          channelId: live
          projectId: mapcss-5b66c
